Repository REAN-Foundation/reancare-service, pull requests merged in 2023-08, with the labels that each got.

#740 Production Deployment
  assets/charts/html.templates/simple.bar.chart.html
  assets/charts/html.templates/stacked.bar.chart.html
  package-lock.json
  package.json
  seed.data/health.systems.and.hospitals.seed..json
  src/api/device.data/webhooks/providers/terra/terra.webhook.controller.ts
  src/api/device.data/webhooks/providers/terra/terra.webhook.routes.ts
  src/auth/authenticator.interface.ts
  src/auth/authenticator.ts
  src/auth/custom/custom.authenticator.ts
  src/database/sql/sequelize/repositories/clinical/lab.record/lab.record.repo.ts
  src/database/sql/sequelize/repositories/clinical/medication/medication.consumption.repo.ts
  src/database/sql/sequelize/repositories/users/patient/health.system.repo.ts
  src/database/sql/sequelize/repositories/users/user/user.task.repo.ts
  src/database/sql/sequelize/repositories/wellness/daily.records/sleep.repo.ts
  src/database/sql/sequelize/repositories/wellness/exercise/physical.activity.repo.ts
  src/database/sql/sequelize/repositories/wellness/nutrition/food.consumption.repo.ts
  src/modules/charts/chart.generator.ts
  src/modules/charts/chart.options.ts
  src/modules/charts/default.chart.options.ts
  src/services/users/patient/statistics/biometrics.stats.ts
  src/services/users/patient/statistics/exercise.stats.ts
  src/services/users/patient/statistics/medication.stats.ts
  src/services/users/patient/statistics/nutrition.stats.ts
  src/services/users/patient/statistics/sleep.stats.ts
  src/services/users/patient/statistics/statistics.service.ts
  src/services/users/patient/statistics/summary.page.ts
  src/services/users/patient/statistics/user.tasks.stats.ts
Labels: enhancement, minor

#741 Update prod-ci-cd.yml
  .github/workflows/prod-ci-cd.yml
  seed.data/cron.schedules.json
  src/api/general/rss.feed/rss.feed.controller.ts
  src/api/general/rss.feed/rss.feed.validator.ts
  src/api/users/user.helper.ts
  src/custom/aha/aha.actions.ts
  src/custom/custom.actions.handler.ts
  src/database/sql/sequelize/models/clinical/donation/donation.record.model.ts
  src/database/sql/sequelize/models/users/patient/health.profile.model.ts
  src/database/sql/sequelize/models/wellness/nutrition/food.consumption.model.ts
  src/database/sql/sequelize/repositories/general/chat.repo.ts
  src/modules/ehr.analytics/models/static.ehr.data.model.ts
  src/modules/reports/pdf.generator.ts
  src/services/general/rss.feed.service.ts
Labels: patch

#742 Update prod-ci-cd.yml
  .github/workflows/prod-ci-cd.yml
Labels: patch

#758 Production deployment
  src/services/webhook/wearable.webhook.service.ts
Labels: enhancement, patch

#759 commented terra pulse and oxygen for time being
  src/services/webhook/wearable.webhook.service.ts
Labels: enhancement, patch
