Repository REAN-Foundation/reancare-service, pull requests merged in 2023-03, with the labels that each got.

#554 updated pr cicd
  .github/workflows/pr-ci-cd.yml
Labels: major

#555 Main2
  .github/workflows/pr-ci-cd.yml
Labels: major

#558 Test/workflow
  .github/workflows/pr-ci-cd.yml
Labels: minor

#602 Hotfix- KCCQ scheduling changes and Body Height API fixes
  seed.data/cron.schedules.json
  src/api/clinical/biometrics/body.height/body.height.validator.ts
  src/custom/aha/quality.of.life/kccq.assessment.utils.ts
  src/database/sql/sequelize/repositories/clinical/biometrics/body.height.repo.ts
  src/database/sql/sequelize/repositories/clinical/biometrics/body.weight.repo.ts
Labels: minor

#621 Create testing_prod.yaml
  .github/workflows/testing_prod.yaml
Labels: minor

#622 Update testing_prod.yaml
  .github/workflows/testing_prod.yaml
Labels: patch
